(define (problem Cool)
   (:domain group25)
   (:objects Heater Cooler TargetT CurrentT)
   (:init (Heat Heater)
          (Cool Cooler)
          (Temperature TargetT)
          (Temperature CurrentT)
          (isGreater CurrentT TargetT)
          (isOff Heater)
          (isOff Cooler)
          )
   (:goal (and(isOff Heater)
              (isON Cooler)
              )))