(define (problem HeatOff)
   (:domain group25)
   (:objects Heater Cooler TargetT CurrentT)
   (:init (Heat Heater)
          (Cool Cooler)
          (Temperature TargetT)
          (Temperature CurrentT)
          (isGreater CurrentT TargetT)
          (isON Heater)
          )
   (:goal (and(isOff Heater)
              )))