(define (problem CoolOff)
   (:domain group25)
   (:objects Heater Cooler TargetT CurrentT)
   (:init (Heat Heater)
          (Cool Cooler)
          (Temperature TargetT)
          (Temperature CurrentT)
          (isLesser CurrentT TargetT)
          (isON Cooler)
          )
   (:goal (and(isOff Cooler)
              )))