(define (problem AllOn)
   (:domain group25)
   (:objects RedL GreenL BlueL)
   (:init (light RedL)
          (light GreenL)
          (light BlueL )
          (isOff RedL)
          (isOff GreenL)
          (isOff BlueL)
          )
   (:goal (and (isON RedL)
               (isOff GreenL)
               (isOff BlueL))))