(define (problem HVAC)
   (:domain group25)
   (:objects Heater Cooler TargetT CurrentT)
   (:init (Appl Heater)
          (Appl Cooler)
          (Temperature TargetT)
          (Temperature CurrentT)
          (isLesser CurrentT TargetT)
          (isOff Heater)
          (isOff Cooler)
          (not(isEqual CurrentT TargetT))
          )
   (:goal (and(isON Heater)
              (isOff Cooler)
              (isEqual TargetT CurrentT)
              (not(isLesser CurrentT TargetT))
              (not(isOff Heater))
              )))