(define (problem AllOff)
   (:domain group25)
   (:objects RedL GreenL BlueL)
   (:init (light RedL)
          (light GreenL)
          (light BlueL )
          (isON RedL)
          (isON GreenL)
          (isON BlueL)
          )
   (:goal (and (isOff RedL)
               (isOff GreenL)
               (isOff BlueL))))